// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FishFooter: typeof import('./src/components/Home/components/fish-footer.vue')['default']
    FishPond: typeof import('./src/components/Home/fish-pond.vue')['default']
    FishPondItem: typeof import('./src/components/Home/components/fish-pond-item.vue')['default']
    HomeTop: typeof import('./src/components/Home/home-top.vue')['default']
    ManagePanel: typeof import('./src/components/ManagePanel/manage-panel.vue')['default']
    ManagePanelLogin: typeof import('./src/components/ManagePanel/manage-panel-login.vue')['default']
    ManagePanelMain: typeof import('./src/components/ManagePanel/manage-panel-main.vue')['default']
    ManagePanelMainAbout: typeof import('./src/components/ManagePanel/components/manage-panel-main-about.vue')['default']
    ManagePanelMainConfig: typeof import('./src/components/ManagePanel/components/manage-panel-main-config.vue')['default']
    ManagePanelMainEnvs: typeof import('./src/components/ManagePanel/components/manage-panel-main-envs.vue')['default']
    ManagePanelMainLinks: typeof import('./src/components/ManagePanel/components/manage-panel-main-links.vue')['default']
    ManagePanelMainStatus: typeof import('./src/components/ManagePanel/components/manage-panel-main-status.vue')['default']
    ManagePanelMainSwitchdb: typeof import('./src/components/ManagePanel/components/manage-panel-main-switchdb.vue')['default']
    RandomPost: typeof import('./src/components/Home/random-post.vue')['default']
  }
}
